{{- if .Values.continuedev.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  namespace: {{ .Values.devspacesNamespace }}
  labels:
    {{- include "ai-workspace.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: che.eclipse.org
data:
  extensions.json: |
    {
      "recommendations": [
        "Continue.continue"
      ]
    }
{{- end }}
