apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ai-workspace.namespace" . }}
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd.managedBy }}
    {{- include "ai-workspace.labels" . | nindent 4 }}
