apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-workspace.pvcName" . }}
  labels:
    opendatahub.io/dashboard: "true"
    {{- include "ai-workspace.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName }}
