{{- if .Values.modelServing.enabled }}
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vllm-runtime
  labels:
    opendatahub.io/dashboard: "true"
    {{- include "ai-workspace.labels" . | nindent 4 }}
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: vLLM NVIDIA GPU ServingRuntime for KServe
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --port=8080
    - --model=/mnt/models
    - "--served-model-name={{`{{.Name}}`}}"
    - --enable-auto-tool-choice
    - "--tool-call-parser={{ include "ai-workspace.modelToolCallParser" . | trim }}"
    {{- $maxLen := include "ai-workspace.modelMaxModelLen" . | trim | int }}
    {{- if gt $maxLen 0 }}
    - "--max-model-len={{ $maxLen }}"
    {{- end }}
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    image: {{ .Values.servingRuntime.image }}
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
{{- end }}
